Document Rollups SDK
ConsenSys/doc.rollups pull request #62
Opened 2022-03-07 20:07 UTC by rolandtyler

# Pull request checklist

## Describe the change
add documentation on Rollups SDK

## Issue fixed
Fixes #59 

## Impacted parts

For content changes:

- [x] Documentation content
- [ ] Documentation page organization

For tool changes:

- [ ] CircleCI workflow
- [ ] Build and QA tools (for example, lint or vale)
- [ ] MkDocs templates
- [ ] MkDocs configuration
- [ ] Python dependencies
- [ ] Node dependencies and JavaScript
- [ ] Read the Docs configuration
- [ ] GitHub integration

## After creating your PR and tests have finished

Make sure that:

- [x] You've [fixed any issues](https://consensys.net/docs/doctools/en/latest/contribute/fix-cicd-errors/) raised by the tests.
- [x] You've [previewed your changes on Read the Docs](https://consensys.net/docs/doctools/en/latest/preview/old-system/#preview-on-read-the-docs)
  and added a [preview link](#preview).

## Preview

2022-03-08 18:27 UTC, alexandratran approved these changes

2022-03-08 19:58 UTC, bgravenorst requested changes
We should add some concept information about this. What does the SDK allow you to do? 
In some of the Concept information about money orders or the workflows, how does the SDK fit into that?

How do you add this to your project? For example, the Besu plugin API you need to ensure your project gradle file contains certain information etc...

2022-04-07 10:38 UTC, NicolasMassart commented on docs/Reference/SDK.md
> +If you need access to the registry, contact us on the [ConsenSys Rollups Discord channel](https://discord.gg/9mCVSY6).
this points me to an archived staking channel. Is this the right invite link?

2022-04-07 20:32 UTC, NicolasMassart approved these changes

2022-05-18 01:58 UTC, bgravenorst commented
@rolandtyler, could you perhaps check if https://github.com/ConsenSys/sumo/pull/2256 also requires any additional work in this PR?

2022-05-18 06:58 UTC, alexandratran commented on docs/Reference/SDK.md
> +[This example](https://github.com/ConsenSys/sumo/blob/main/manager/web3j-sdk-examples/src/main/java/net/consensys/sumo/web3j/sdk/example/Web3jSdkExample.java)
```suggestion
[This example](https://github.com/ConsenSys/sumo/tree/main/sdk/web3j-sdk-examples)
```

This link no longer works. I replaced with a link to the example directory with the useful readme.

2022-05-18 06:58 UTC, alexandratran commented on docs/Reference/SDK.md
> +* Redeem money order
```suggestion
demonstrates how to use the SDK by:

* Creating accounts.
* Retrieving account IDs.
* Requesting money order creation.
* Redeeming money orders.
```

2022-05-18 07:01 UTC, alexandratran commented
@bgravenorst looks like https://github.com/ConsenSys/sumo/pull/2174 should be documented on the JSON-RPC API methods page (see https://github.com/ConsenSys/doc.rollups/issues/68).

2022-11-22 18:46 UTC, closed without merging